# Tên của quy trình tự động
name: Deploy Vite App to GitHub Pages

on:
  # Chạy mỗi khi có push lên nhánh main
  push:
    branches: [ "main" ]
  # Cho phép bạn chạy thủ công từ tab Actions
  workflow_dispatch:

# Phân quyền cho quy trình
permissions:
  contents: read
  pages: write
  id-token: write

# Thiết lập môi trường deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Bạn có thể đổi thành phiên bản Node.js bạn dùng
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        # Chạy lệnh build, sử dụng base path là tên repository của bạn
        run: npm run build -- --base=/Content-Spark-AI/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4